name: Bonmenu
options:
  bundleIdPrefix: com.bonmenu
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
    INFOPLIST_FILE: Bonmenu/Resources/Info.plist
    CODE_SIGN_ENTITLEMENTS: Bonmenu/Resources/Bonmenu.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  Bonmenu:
    type: application
    platform: macOS
    sources:
      - path: Bonmenu
        excludes:
          - "Resources/Info.plist"
          - "Resources/Bonmenu.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bonmenu.app
        PRODUCT_NAME: Bonmenu
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Bonmenu/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Bonmenu/Resources/Bonmenu.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: NO
    info:
      path: Bonmenu/Resources/Info.plist
    entitlements:
      path: Bonmenu/Resources/Bonmenu.entitlements
